### PR TITLE
chore: replace danger token due to rotation

### PR DESCRIPTION
**Pull request by crazyoptimist**

### CODE REVIEW

**Comment by crazyoptimist** [comment]
Not sure why it fails in `ruby-2.7.2`.

**Comment by crazyoptimist** [comment]
Another thing I wonder is that CI always uses mongoid latest version(8.0.3 as of now), no matter what version you specified in the workflow version matrix. I've checked the test logs for all cases and they all installed mongoid 8.0.3.

**Comment by dblock** [comment]
Database versions should be locked down for where they auto-updated. Likely the cause of failures in the CI.

**Comment by crazyoptimist** [comment]
Fixed the mongoid version lock down, but it still fails in ruby-2.7.2.

```bash
An error occurred while loading ./spec/slack-ruby-bot-server-events/config_spec.rb.                                                                                        Failure/Error: require 'slack-ruby-bot-server'                                                                                                                                                                                                                                                                                                        SyntaxError:                                                                                                                                                                 /home/debian/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/console-1.16.2/lib/console/progress.rb:77: syntax error, unexpected ')'                                                              @output.info(@subject, ...)                                                                                                                                                                          ^                                                                                                                          /home/debian/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/console-1.16.2/lib/console/progress.rb:106: syntax error, unexpected end-of-input, expecting `end'
# ./lib/slack-ruby-bot-server-events.rb:3:in `require'
# ./lib/slack-ruby-bot-server-events.rb:3:in `<top (required)>'
# ./spec/spec_helper.rb:6:in `<top (required)>'
# ./spec/slack-ruby-bot-server-events/config_spec.rb:3:in `require'
# ./spec/slack-ruby-bot-server-events/config_spec.rb:3:in `<top (required)>'
```

**Comment by crazyoptimist** [comment]
Ended up dropping the ruby version 2.7.2.
Everything is green with 2.6.2 and 3.1.0.
Locally I also tried with mongoid 8.0.3 and ruby 3.1.3, turned green.

**Comment by dblock** [comment]
The 2.7.2 problem is https://github.com/socketry/console/issues/37.

Seems like Ruby 2.7.3 would have worked. Want to try?

**Comment by crazyoptimist** [comment]
You are right. I tried Ruby 2.7.3 on my machine and it turned green.
But I think we are good enough with 2.6.2?

**Comment by dblock** [comment]
I think we wanted to have some more rubies coverage to find problems like these. Leaving it as is also works for me.

**Pull request merged**
